### ISSUE TITLE
An abstraction for directories?

### ISSUE THREAD

**Issue by maasg** [pathikrit/better-files#103]
I'm new to better-files, so apologies if this has been discussed before and I did not find it during my search.
In my journey to migrate from a mess of `java.io.File` and `java.nio.file._` use, one of the abstractions that I would like to have in a library like better-files is that of a `Directory`. While in general, the `File` abstraction works well, I would like to restrict certain operations to take Directories as arguments. 

Is there something available in better-files?  (Right now I'm writting some implicits to deal with that)
If not, why not?

**Comment by pathikrit** [comment]
Very good question. In fact there was some mechanism to capture a `Directory` that I recently removed here: https://github.com/pathikrit/better-files/commit/54af6d359a3031bddc3f5e6700ccb1a3ef578d40

My reasons:
1. There are more types of things than simple files, directories and symlinks e.g. on Unix there are process files and device files and on a s3 filesystem everything is a file

2. Say we went with this ADT:
```scala
sealed trait File
object File {
  def apply(path: String): File
  case class Directory(path: String) extends File
  case class RegularFile(path: String) extends File
}
``` 
Now, everytime you want to instantiate a `File`, you have to do side-effect IO to check if its a directory or not. This is surprising behavior (constructor to do I/O)

3. Some things become weird e.g. if a file does not exist yet - is it a Directory or a RegularFile?

4. Other things like `File.walk` and `File.list` become expensive.

---
I think a long-term solution to this problem is to separate out into 2 classes:

1. Path:
* Paths are simply strings pointing to files on the file system
* A path may or may not have a file on the filesystem associated with it
* Any APIs related to Path do not do I/O

2. Files have a `has-a` relationship with Path
* All File APIs do I/O
* Files have a strongly-typed ADT of
