### ISSUE TITLE
Unicode BOM support ?

### ISSUE THREAD

**Issue by ronanM** [pathikrit/better-files#107]
https://en.wikipedia.org/wiki/Byte_order_mark

`better.files.File#lines` seems to not support BOM.

**Comment by pathikrit** [comment]
Hi, better-files just calls `java.nio.file.Files.readAllLines` - so its not really a bug in this library but in Java itself. They decided to not fix the issue here: http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4508058

I plan to address this in better-files by

* [ ] Skipping BOM by default for UTF-8
* [ ] Introduce a [new chartset](https://github.com/google/guava/issues/345#issuecomment-61350339) (`X-UTF-8-BOM`) in case user expects the current Java behaviour
