### ISSUE TITLE
GlobSpec RegEx tests fail on Windows

### ISSUE THREAD

**Issue by brentax** [pathikrit/better-files#120]
I fixed the other tests in `GlobSpec` in my PR https://github.com/pathikrit/better-files/pull/119

The two remaining failing tests on Windows are due to RegEx's that use `/` instead of `\`, checking for Unix slashes rather than Windows slashes.

I see two options:

1. Call this expected behavior. Have these tests use different regex's depending on the OS
2. Try to automatically switch the slashes when running on Windows

**Comment by jaa127** [comment]
Hello, thanks for looking into this and testing this on Windows.

If tests in question are: 
     
    "use parent dir for matching (e.g. plain 'subdir/*.ext' instead of '**/subdir/*.ext)"

and 

    "Regex" should "match all txt-files  under sub-directory (e.g. '.*/.*\\\\.txt')"

then it would make sense to parametrize path sep in those tests and use that param instead of hard coded value.  Only twistt is that windows sep have to be escaped. Unfortunately I can not test that code path on windows.
