### ISSUE TITLE
monadic I/O ?

### ISSUE THREAD

**Issue by pathikrit** [pathikrit/better-files#30]
Create a better-files-cats which overwrites the side-effecty APIs of Files.scala with monadic ops from cats or IO monad from scalaz

**Comment by BusyByte** [comment]
I've been struggling with this library a bit in using it with cats Xor (XorT etc..) (I'm still on Scala 2.11) because I have to catch exceptions everywhere.  It would be nice to have a functional interface which doesn't throw exceptions using Xor (Scala 2.11) or Either (Scala 2.12).  I'd be fine if it was not part of the core but an optional module.

**Comment by jvican** [comment]
@BusyByte We have been discussing this several times in the Scala Platform meetings and discussions.
  
I think it would be great if such a functional layer exists. We're accepting contributions on this front. Would you make a PR to include it? We can help you out getting all the details right and I'm sure the Typelevel folks will be interesting in contributing to this, too (/cc @tpolecat @milessabin).

**Comment by pathikrit** [comment]
better-files just provides a safer (and more baseline traditional Scala idiomatic) wrapper around the idiosyncrasies of the Java NIO. Other higher level abstractions needs to be built on top of better files as a separate module that depends on vanilla better-files. Take a look at the akka-file-watcher or the shapeless-scanner as examples.

**Comment by tpolecat** [comment]
So, I have been through this exercise with database I/O and have a few general thoughts. 

**To be clear** it's not practical to do any of this without library support for functional/monadic programming, which means cats or scalaz. There really is no more minimal "core" that can be pulled out (this is what cats is).

**Regarding `IO`-like data types**, Cats doesn't provide a data type that understands side-effects, but monix and fs2 both provide `Task` implementations that are equivalent in principle to scalaz `Task`, which is (again in principle) a more general `IO` with an async constructor. So there are a number of options that we would like to abstract over.

However, abstracting over these data types is tricky because the fundamental operations (capture a side-effect as a value, trap and propagate exceptions, side-effect to produce a value) don't give rise to identities … we say they are "lawless". This means that any abstraction over IO-like types will need some careful thought and a test kit to ensure that instances are consistent with the desired semantics. I'm going to be talking to some people at NEScala about this problem so maybe we'll have something concrete to discuss in a few weeks. doobie and http4s need to support both scalaz and cats and are driving this effort.

**Regarding laziness and resource safety**, i.e., things like iostream-backed `Iterator`s, it's very hard in general to talk about lazy/streaming IO because you need to track the effects throughout the lifetime of the underlying resource (reading from such an iterator is a side-effect) and you need to ensure that resources are cleaned up in all cases, even if the stream isn't fully consumed. This is the central problem addressed by scalaz-stream and fs2, and I would suggest using these instead of trying to make better-files streaming APIs safe. It is very very hard to do this correctly.

So I suggest going slowly and defining very clearly what the desired outcome is. I have done a lot of this and am happy to share my experiences if it's helpful.

**Comment by pathikrit** [comment]
After feedback from the community,I decided this is out of scope of better-files whose goal is to simply wrap over the JDK APIs. Recommended approach is to simply wrap better-files calls with [your preferred IO monad](https://github.com/typelevel/cats-effect)
