### ISSUE TITLE
Wrap over java.nio types instead of exposing them directly

### ISSUE THREAD

**Issue by mdedetrich** [pathikrit/better-files#97]
This is in response to https://contributors.scala-lang.org/t/adding-better-files-to-the-scala-platform

In regards to cross platform support it would be ideal if better-files wrapped over `java.nio` instead of exposing them directly. This would make it much easier to support better files API over different platforms which have differing capabilities and designs when it comes to IO support.

**Comment by pathikrit** [comment]
`better-files` is intended to be the thin proxy to Java IO. It is intended to be used in the JVM implementation of a cross platform Scala File class.

What you suggest is nice but I don't know how to go about designing a `trait File {}` which will make everyone (JVM, scala-native, ScalaJs) happy. I would be happy to accept PRs on this. Feel free to just check-in the trait and we can fill it out with implementation later.

**Comment by mdedetrich** [comment]
Sure thing, will try it out next week sometime and will see how it goes

**Comment by pathikrit** [comment]
Hi I am going to close this because:

1) `better-files` is not intended to be a cross platform Scala library but just the wrapper for Java's NIO.

2) A unified File data-type that makes everyone in Scala happy is out of the scope of this library and requires lots of discussions with vested parties.

3) Scala native team will already port Java NIO - so better-files would be compatible with Scala native once that is done.
